name: VerifiedCommands
version: 1.0
main: com.pzg.www.minecrafthook.verifycommands.main.PluginMain
description: This plugin adds a set of commands fired when a user is verified with the Discord Minecraft Hook Bot.
author: TJPlaysNow
depend: [Discord-Bot-API, MinecraftHook]